global:
    scrape_interval: 10s
    evaluation_interval: 10s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['host.docker.internal:9090']
    - job_name: 'roman-numeral-app'
      scrape_interval: 5s
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: [ 'host.docker.internal:8090' ]
    - job_name: 'tempo'
      static_configs:
        - targets: ['host.docker.internal:3200']
